In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Task 1

Part A: Data Collection and Preprocessing
- Perform the following steps:
- Load the dataset using Pandas
- Display the first 5 rows
- Check dataset dimensions
- Identify missing values
- Remove or handle null values
- Convert required columns into numerical datatype
- Remove duplicate records if present
- Generate statistical summary
- Select appropriate dependent and independent variables

In [27]:
# Loading the dataset

data = pd.read_csv("Student Awareness Survey.csv")

In [28]:
# Displaying the first 5 rows

data.head()

,Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester
0,69,3.40,98
1,75,3.69,95
2,82,3.41,95
3,91,3.60,92
4,70,3.54,93

In [29]:
# Checking dataset dimensions

data.shape

(50, 3)

The dataset has 50 rows and 3 columns

In [30]:
# Checking basic info

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Your CIA % of last semester                   50 non-null     str
 1   Your GPA of last semester                     50 non-null     float64
 2   Your maximum attendance % till last semester  50 non-null     str
dtypes: float64(1), str(2)
memory usage: 1.5 KB

In [31]:
data.describe()

       Your GPA of last semester
count                  50.000000
mean                    3.497000
std                     0.690865
min                     2.740000
25%                     3.305000
50%                     3.400000
75%                     3.600000
max                     8.000000

Only GPA is being treated as a float value, the rest need to be converted. For that, standardization will be required first as there are inconsistencies.

In [32]:
data["Your maximum attendance % till last semester"]

0         98
1         95
2         95
3         92
4         93
5         98
6         94
7         85
8         90
9         93
10        95
11        95
12        95
13       85%
14       100
15        85
16        88
17      91 %
18       100
19     96.54
20        95
21        90
22       95%
23       98%
24    94.70%
25        93
26        96
27        93
28        99
29        90
30       100
31        92
32       95%
33        94
34       89%
35        88
36        97
37        95
38       100
39       89%
40        96
41        96
42        92
43       93%
44        95
45        95
46        97
47       97%
48        90
49        94
Name: Your maximum attendance % till last semester, dtype: str

In [ ]:
# Getting rid of the % sign and converting the column to float type

data["Your maximum attendance % till last semester"] = data["Your maximum attendance % till last semester"].str.rstrip("%").astype(float)

In [ ]:
data.info() # verifying it

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Your CIA % of last semester                   50 non-null     str
 1   Your GPA of last semester                     50 non-null     float64
 2   Your maximum attendance % till last semester  50 non-null     float64
dtypes: float64(2), str(1)
memory usage: 1.4 KB

In [33]:
data["Your CIA % of last semester"]

0         69
1         75
2         82
3         91
4         70
5         75
6         74
7         68
8         73
9         79
10        72
11        80
12        78
13         7
14        70
15        60
16        68
17      71 %
18        64
19     71.78
20        70
21        63
22       76%
23       83%
24       80%
25        72
26        70
27        70
28        71
29        77
30        80
31        80
32       80%
33        70
34       85%
35        71
36        68
37        67
38        72
39      65 %
40        76
41      75.2
42     69.78
43    71.11%
44     79.56
45        75
46        70
47       62%
48       66%
49        63
Name: Your CIA % of last semester, dtype: str

In [37]:
# Getting rid of the % sign and converting the column to float type again

data["Your CIA % of last semester"] = data["Your CIA % of last semester"].str.rstrip("%").astype(float)

In [ ]:
data.info() # verifying again

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Your CIA % of last semester                   50 non-null     float64
 1   Your GPA of last semester                     50 non-null     float64
 2   Your maximum attendance % till last semester  50 non-null     float64
dtypes: float64(3)
memory usage: 1.3 KB

In [39]:
data[["Your maximum attendance % till last semester", "Your CIA % of last semester"]]

    Your maximum attendance % till last semester  Your CIA % of last semester
0                                          98.00                        69.00
1                                          95.00                        75.00
2                                          95.00                        82.00
3                                          92.00                        91.00
4                                          93.00                        70.00
5                                          98.00                        75.00
6                                          94.00                        74.00
7                                          85.00                        68.00
8                                          90.00                        73.00
9                                          93.00                        79.00
10                                         95.00                        72.00
11                                         95.00                        80.00
12                                         95.00                        78.00
13                                         85.00                         7.00
14                                        100.00                        70.00
15                                         85.00                        60.00
16                                         88.00                        68.00
17                                         91.00                        71.00
18                                        100.00                        64.00
19                                         96.54                        71.78
20                                         95.00                        70.00
21                                         90.00                        63.00
22                                         95.00                        76.00
23                                         98.00                        83.00
24                                         94.70                        80.00
25                                         93.00                        72.00
26                                         96.00                        70.00
27                                         93.00                        70.00
28                                         99.00                        71.00
29                                         90.00                        77.00
30                                        100.00                        80.00
31                                         92.00                        80.00
32                                         95.00                        80.00
33                                         94.00                        70.00
34                                         89.00                        85.00
35                                         88.00                        71.00
36                                         97.00                        68.00
37                                         95.00                        67.00
38                                        100.00                        72.00
39                                         89.00                        65.00
40                                         96.00                        76.00
41                                         96.00                        75.20
42                                         92.00                        69.78
43                                         93.00                        71.11
44                                         95.00                        79.56
45                                         95.00                        75.00
46                                         97.00                        70.00
47                                         97.00                        62.00
48                                         90.00                        66.00
49                                         94.00                        63.00

In [ ]:
data.describe() # getting statistical summary