In [46]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Problem Statement
### Using the dataset collected from the class survey form, perform Simple Linear Regression analysis to determine whether:
- CIA percentage can predict GPA
- Attendance percentage can predict GPA

# Task 1

### Part A: Data Collection and Preprocessing

1. Load the dataset using Pandas

In [20]:
# Loading the dataset

data = pd.read_csv("Student Awareness Survey.csv")

2. Display the first 5 rows

In [21]:
# Displaying the first 5 rows

data.head()

,Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester
0,69,3.40,98
1,75,3.69,95
2,82,3.41,95
3,91,3.60,92
4,70,3.54,93

3. Check dataset dimensions

In [22]:
# Checking dataset dimensions

data.shape

(50, 3)

The dataset has 50 rows and 3 columns

4. Identify missing values

In [23]:
# Checking for missing values

data.isnull().sum()

Your CIA % of last semester                     0
Your GPA of last semester                       0
Your maximum attendance % till last semester    0
dtype: int64

5. Remove or handle null values

In [24]:
# There weren't any null/missing values in the dataset, as seen from the code executed above.

6. Convert required columns into numerical datatype

In [25]:
# Checking basic info, including non-null counts and data types

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Your CIA % of last semester                   50 non-null     str
 1   Your GPA of last semester                     50 non-null     float64
 2   Your maximum attendance % till last semester  50 non-null     str
dtypes: float64(1), str(2)
memory usage: 1.5 KB

CIA % and attendance % are being treated as string values.

In [26]:
data.describe()

       Your GPA of last semester
count                  50.000000
mean                    3.497000
std                     0.690865
min                     2.740000
25%                     3.305000
50%                     3.400000
75%                     3.600000
max                     8.000000

Only GPA is being treated as a float value, the rest need to be converted. For that, standardization will be required first as there are inconsistencies.

In [27]:
data["Your maximum attendance % till last semester"]

0         98
1         95
2         95
3         92
4         93
5         98
6         94
7         85
8         90
9         93
10        95
11        95
12        95
13       85%
14       100
15        85
16        88
17      91 %
18       100
19     96.54
20        95
21        90
22       95%
23       98%
24    94.70%
25        93
26        96
27        93
28        99
29        90
30       100
31        92
32       95%
33        94
34       89%
35        88
36        97
37        95
38       100
39       89%
40        96
41        96
42        92
43       93%
44        95
45        95
46        97
47       97%
48        90
49        94
Name: Your maximum attendance % till last semester, dtype: str

In [28]:
# Getting rid of the % sign and converting the column to float type

data["Your maximum attendance % till last semester"] = data["Your maximum attendance % till last semester"].str.rstrip("%").astype(float)

In [29]:
data.info() # verifying it

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Your CIA % of last semester                   50 non-null     str
 1   Your GPA of last semester                     50 non-null     float64
 2   Your maximum attendance % till last semester  50 non-null     float64
dtypes: float64(2), str(1)
memory usage: 1.4 KB

In [30]:
data["Your CIA % of last semester"]

0         69
1         75
2         82
3         91
4         70
5         75
6         74
7         68
8         73
9         79
10        72
11        80
12        78
13         7
14        70
15        60
16        68
17      71 %
18        64
19     71.78
20        70
21        63
22       76%
23       83%
24       80%
25        72
26        70
27        70
28        71
29        77
30        80
31        80
32       80%
33        70
34       85%
35        71
36        68
37        67
38        72
39      65 %
40        76
41      75.2
42     69.78
43    71.11%
44     79.56
45        75
46        70
47       62%
48       66%
49        63
Name: Your CIA % of last semester, dtype: str

In [31]:
# Getting rid of the % sign and converting the column to float type again

data["Your CIA % of last semester"] = data["Your CIA % of last semester"].str.rstrip("%").astype(float)

In [32]:
data.info() # verifying again

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Your CIA % of last semester                   50 non-null     float64
 1   Your GPA of last semester                     50 non-null     float64
 2   Your maximum attendance % till last semester  50 non-null     float64
dtypes: float64(3)
memory usage: 1.3 KB

In [33]:
data[["Your maximum attendance % till last semester", "Your CIA % of last semester"]]

    Your maximum attendance % till last semester  Your CIA % of last semester
0                                          98.00                        69.00
1                                          95.00                        75.00
2                                          95.00                        82.00
3                                          92.00                        91.00
4                                          93.00                        70.00
5                                          98.00                        75.00
6                                          94.00                        74.00
7                                          85.00                        68.00
8                                          90.00                        73.00
9                                          93.00                        79.00
10                                         95.00                        72.00
11                                         95.00                        80.00
12                                         95.00                        78.00
13                                         85.00                         7.00
14                                        100.00                        70.00
15                                         85.00                        60.00
16                                         88.00                        68.00
17                                         91.00                        71.00
18                                        100.00                        64.00
19                                         96.54                        71.78
20                                         95.00                        70.00
21                                         90.00                        63.00
22                                         95.00                        76.00
23                                         98.00                        83.00
24                                         94.70                        80.00
25                                         93.00                        72.00
26                                         96.00                        70.00
27                                         93.00                        70.00
28                                         99.00                        71.00
29                                         90.00                        77.00
30                                        100.00                        80.00
31                                         92.00                        80.00
32                                         95.00                        80.00
33                                         94.00                        70.00
34                                         89.00                        85.00
35                                         88.00                        71.00
36                                         97.00                        68.00
37                                         95.00                        67.00
38                                        100.00                        72.00
39                                         89.00                        65.00
40                                         96.00                        76.00
41                                         96.00                        75.20
42                                         92.00                        69.78
43                                         93.00                        71.11
44                                         95.00                        79.56
45                                         95.00                        75.00
46                                         97.00                        70.00
47                                         97.00                        62.00
48                                         90.00                        66.00
49                                         94.00                        63.00

7. Remove duplicate records if present

In [38]:
# Checking for duplicate rows

data.duplicated().sum()

np.int64(0)

There are no duplicate values

8. Generate statistical summary

In [34]:
data.describe() # getting statistical summary

,Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester
count,50.000000,50.000000,50.000000
mean,71.508600,3.497000,93.824800
std,11.247756,0.690865,3.852926
min,7.000000,2.740000,85.000000
25%,69.195000,3.305000,92.000000
50%,71.445000,3.400000,95.000000
75%,76.750000,3.600000,96.000000
max,91.000000,8.000000,100.000000

Average CIA % of the class is 71.50 %, with the lowest being 7 % and the highest being 91 %.

Average GPA % of the class is 3.49, with the lowest being 2.74 and the highest being 8, but this could be an outlier, on the assumption that the user filled it on the basis of CGPA (10 point scale) and not GPA (4 point scale), as the median distributions are around the ranges of 3.3, 3.4 and 3.6.

Average attendance % of the class is 93.82 %, with the lowest being 85 % and the highest being 100 %.

9. Select appropriate dependent and independent variables

In [41]:
# Changing column names first for better readability

renamed_columns = {
    "Your CIA % of last semester": "CIA_Percentage",
    "Your GPA of last semester": "GPA",
    "Your maximum attendance % till last semester": "Attendance_Percentage"
}

data = data.rename(columns = renamed_columns)
data.head()

   CIA_Percentage   GPA  Attendance_Percentage
0            69.0  3.40                   98.0
1            75.0  3.69                   95.0
2            82.0  3.41                   95.0
3            91.0  3.60                   92.0
4            70.0  3.54                   93.0

GPA - dependent variable, as we're trying to predict if CIA_Percentage and Attendance_Percentage can predict GPA.

CIA_Percentage and Attendance_Percentage - independent variables.

Experiment 1: Whether CIA percentage can predict GPA; GPA - dependent, CIA_Percentage - independent

Experiment 2: Whether Attendance percentage can predict GPA; GPA - dependent, Attendence_Percentage - independent.

### Part B: Simple Linear Regression using Scikit-learn

### Experiment 1:

Independent Variable (X):

- CIA Percentage

Dependent Variable (Y):

- GPA

In [56]:
# Setting the independent and dependent variables

X = data[["CIA_Percentage"]]
y = data["GPA"]

1. Split the dataset into training and testing sets

In [57]:
# Splitting the dataset into training (80%) and testing (20%) sets, meaning that the model will be trained on 80% of the data and evaluated on the remaining 20%. The random_state parameter is set to 42 to ensure reproducibility of the results.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
lr = LinearRegression() # creating an instance of the model
lr.fit(X_train, y_train) # trains the data (80% of the data), where X_train trains on the features and y_train trains on the target variable

LinearRegression()

In [59]:
y_pred = lr.predict(X_test) # making predictions on the test set (20% of the data) using the trained model

In [60]:
comparison_cia_percentage = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison_cia_percentage.head()

   Actual  Predicted
0    8.00   2.555063
1    3.30   3.296486
2    3.79   3.488233
3    3.66   3.424317
4    3.40   3.373185

In [66]:
sample_input_cia = pd.DataFrame([[72]], columns = ["CIA_Percentage"])
sample_prediction_cia = lr.predict(sample_input_cia)
sample_prediction_cia

array([3.38596787])